### ISSUE TITLE
Hi, does is possible to mgirate this project to UE based?

### ISSUE THREAD

**Issue by jinfagang** [Danial-Kord/DigiHuman#7]
Hi, does is possible to mgirate this project to UE based?

**Comment by jinfagang** [comment]
@Danial-Kord thank u. It's promising. I would hoping for a UE5 version expecially if it can work on metahuman. It would be awesome. Nice work.

**Comment by jinfagang** [comment]
BTW, I am consider make a model based face mocap (without iPhone) using blendshapes, it would be more natural than using mesh or 3d poses. I might PR to u when I finished, so that a more vivid metahuman version could came out.

**Comment by Danial-Kord** [comment]
> @Danial-Kord thank u. It's promising. I would hoping for a UE5 version expecially if it can work on metahuman. It would be awesome. Nice work.

Thank you for your comment ^_^

**Comment by Danial-Kord** [comment]
> BTW, I am consider make a model based face mocap (without iPhone) using blendshapes, it would be more natural than using mesh or 3d poses. I might PR to u when I finished, so that a more vivid metahuman version could came out.

Wow, that is great. Exactly one of the ways to expand this project is to use a deep neural network model to detect every blend shape weight. That would be awsome good luck :D

**Comment by jinfagang** [comment]
@Danial-Kord do u have any estimated timeline on come up with a ue version? I like to test it with mediapipe, not very familliar with unity

**Comment by Danial-Kord** [comment]
> @Danial-Kord do u have any estimated timeline on come up with a ue version? I like to test it with mediapipe, not very familliar with unity

Well currently I am focusing on adding more features. 
But I think in the next 6 months we can have a UE version of the application available.

**Comment by jinfagang** [comment]
@Danial-Kord do u have a discord or telegram? we can further close discuss on detailed topic.

**Comment by Danial-Kord** [comment]
Yeah sure,
Here is my telegram ID: https://t.me/Danial_km

**Comment by ujjawalcse** [comment]
Hey @Danial-Kord @jinfagang ,
May i join too, to achieve our common goal towards Metahuman.

**Comment by jinfagang** [comment]
@ujjawalcse sure, add my telegram, let's talk in a group: `lucasjinreal`

**Comment by ujjawalcse** [comment]
Found @Danial-Kord on telegram but couldn't find you @jinfagang .
you can connect me with @ujjawal_ks.
